server:
  port: 8086
  servelet:
    context-path: /rest
   
spring:
  application:
     name: "Generating xml response from rest api"
  main:
     banner-mode: "off"
  jpa:
     database: h2
     hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: create-drop
  h2:
     console:
        enabled: true

logging:
  level:
     org: 
        springframework: Error

     
          